name: On Demand Revalidation
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'production'

    steps:
      - uses: actions/checkout@v3

      - name: echo token
        env:
          TOKEN: ${{  secrets.REVALIDATION_TOKEN}}
        run: |
          echo "token is $TOKEN"
          echo "https://www.akladyous.it/api/revalidate?path=blog&token=$TOKEN"
          echo "https://www.akladyous.it/api/revalidate?token=$TOKEN&path=blog"

      - name: validate endpoint
        env:
          TOKEN: ${{  secrets.REVALIDATION_TOKEN}}
        run: |
          curl -X GET "https://www.akladyous.it/api/revalidate?token=$TOKEN&path=blog"
