# This is a basic workflow to help you get started with Actions

name: On Demand Revalidation
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 'production'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: echo token
        env:
          revalidation_token: ${{  secrets.REVALIDATION_TOKEN}}
        run: echo "token is $REVALIDATION_TOKEN"

      - name: validate endpoint
        run: |
          curl -X GET "https://www.akladyous.it/api/revalidate?path=blog&token=%REVALIDATION_TOKEN"
