# This is a basic workflow to help you get started with Actions

name: On Demand Revalidation
env:
  GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: validate endpoint
        run:
          curl -X GET "https://www.akladyous.it/api/revalidate?path=blog&token=${{
          secrets.GITHUB_TOKEN }}"
      - name: echo data
        run: echo "token " >> $GIT_TOKEN
