name: On Demand Revalidation

on:
    push:
        branches: ["main"]
        paths:
            - "posts/**"
            - "images/**"
    workflow_dispatch:
        inputs:
            environment:
                description: "The environment to deploy to"
                required: true
                default: "production"
jobs:
    build:
        runs-on: ubuntu-latest
        environment: "production"

        steps:
            - uses: actions/checkout@v3

            - name: 'validate endpoint'
                env:
                    TOKEN: ${{ secrets.REVALIDATION_TOKEN }}
                run: |
                    curl -X GET "https://www.boula.dev/api/revalidate?token=$TOKEN&path=blog"
